# Generated by Django 4.2.2 on 2023-06-16 17:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('article_id', models.UUIDField(editable=False)),
                ('pub_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
